### PR TITLE
Update .bowerrc

### PR DESCRIPTION
**Pull request by bdjunayed**
Update bower components path to folder "vendor".

### CODE REVIEW

**Comment by pedzed** [comment]
Why do you want `vendor/bower_components` over `public/vendor/bower`?

**Comment by bdjunayed** [comment]
Bower seems to be 3rd party vendor tools, thus it may put beside the node_ folder. As we can change its path we may put it in vendor/bower_components/ folder.

**Comment by pedzed** [comment]
But you will call them, right? So you _need_ them in the public directory.

**Comment by bdjunayed** [comment]
We would copy necessary the fonts to the 'public/assets/fonts' directory from the '\vendor\bower' folder. We don't need to put all the bower components in the public folder, I think.
Like I can call susy directly from /vendor folder don't need to attach it to the /public folder. 
The contributors have to do is run bower install command, no unnecessary file will be in the public folder. Thus we can simplify our public folder. We may think like this.

**Comment by pedzed** [comment]
Thanks for your suggestion, but I prefer what we currently have. If you want it somewhere else, you can always easily change it to your own way.

**Comment by bdjunayed** [comment]
Welcome! it's alright.

**Pull request closed without merging**
